<a href="https://colab.research.google.com/github/nataliaaa14/ML_2024/blob/Case_study_1/Casestudy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
import numpy as np
from sklearn.metrics import precision_score, recall_score, f1_score
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler, SMOTE
from imblearn.under_sampling import NearMiss
from sklearn.model_selection import cross_val_score, RepeatedStratifiedKFold
# from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from imblearn.pipeline import Pipeline 
from imblearn.pipeline import make_pipeline
from sklearn.metrics import classification_report
import time
import plotly.express as px


In [35]:
dane=pd.read_csv("../datasets/creditcard.csv")

In [36]:
dane.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [37]:
X_data=dane.iloc[:, 1:-2] #bez amount
y_data=dane.iloc[:,-1]

In [38]:
y_data.value_counts()/y_data.value_counts().sum()

Class
0    0.998273
1    0.001727
Name: count, dtype: float64

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X_data, y_data, test_size=0.2, random_state=42)

In [7]:
knn_classifier = KNeighborsClassifier(n_neighbors=5)  

knn_classifier.fit(X_train, y_train)

y_pred = knn_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

0.9995259997893332
[[56859     5]
 [   22    76]]


In [8]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f'Dokładność: {accuracy:.4f}')
print(f'Precyzja: {precision:.4f}')
print(f'Czułość: {recall:.4f}')
print(f'F1-score: {f1:.4f}')

Dokładność: 0.9995
Precyzja: 0.9383
Czułość: 0.7755
F1-score: 0.8492


In [9]:
ros=RandomOverSampler()
X_train_ros, y_train_ros = ros.fit_resample(X_train, y_train)

y_train_ros.value_counts()

Class
0    227451
1    227451
Name: count, dtype: int64

In [11]:
knn_classifier = KNeighborsClassifier(n_neighbors=5)  

knn_classifier.fit(X_train_ros, y_train_ros)

y_pred = knn_classifier.predict(X_test)

conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

[[56833    31]
 [   14    84]]


In [30]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f'Dokładność: {accuracy:.4f}')
print(f'Precyzja: {precision:.4f}')
print(f'Czułość: {recall:.4f}')
print(f'F1-score: {f1:.4f}')

Dokładność: 0.9942
Precyzja: 0.2167
Czułość: 0.8980
F1-score: 0.3492


In [15]:
undersample = NearMiss(version=3)
undersample = NearMiss(version=3, n_neighbors=3)
# transform the dataset
X_train_nm, y_train_nm = undersample.fit_resample(X_train, y_train)

y_train_nm.value_counts()

c:\Users\HP 840 G3\AppData\Local\Programs\Python\Python312\Lib\site-packages\imblearn\under_sampling\_prototype_selection\_nearmiss.py:203: UserWarning: The number of the samples to be selected is larger than the number of samples available. The balancing ratio cannot be ensure and all samples will be returned.
  warnings.warn(


Class
1    394
0    328
Name: count, dtype: int64

In [21]:
smote=SMOTE(sampling_strategy=0.1)
X_smote, y_smote =smote.fit_resample(X_data, y_data)
rus=RandomUnderSampler(sampling_strategy=0.5)
X_rus, y_rus =rus.fit_resample(X_smote, y_smote)

In [31]:
model=make_pipeline(knn_classifier)
over=SMOTE(sampling_strategy=0.1)
under=RandomUnderSampler(sampling_strategy=0.5)
pipeline=make_pipeline(over,under,model)
    

In [32]:
pipeline.fit(X_train, y_train)
y_pred=pipeline.predict(X_test)
print(classification_report(y_test,y_pred))


              precision    recall  f1-score   support

           0       1.00      0.99      1.00     56864
           1       0.22      0.90      0.35        98

    accuracy                           0.99     56962
   macro avg       0.61      0.95      0.68     56962
weighted avg       1.00      0.99      1.00     56962



In [46]:
#LogisticRegression
weights={0: 1.0, 1: 1.0}
model=LogisticRegression(solver='lbfgs',class_weight=weights)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

0.9991046662687406
[[56855     9]
 [   42    56]]


In [47]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f'Dokładność: {accuracy:.4f}')
print(f'Precyzja: {precision:.4f}')
print(f'Czułość: {recall:.4f}')
print(f'F1-score: {f1:.4f}')

Dokładność: 0.9991
Precyzja: 0.8615
Czułość: 0.5714
F1-score: 0.6871


In [48]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.86      0.57      0.69        98

    accuracy                           1.00     56962
   macro avg       0.93      0.79      0.84     56962
weighted avg       1.00      1.00      1.00     56962

